version: '3'
services:
 docker-postgres:
    image: postgres:10.4
    environment:
      - POSTGRES_DB=invillia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=invillia
#      
#  keycloak-server:
#    image: keycloak-server-image
#    ports:
#      - 8080:8080  
#  eureka-server:
#    image: eureka-server-image
#    ports:
#      - 8081:8080
#      
#  zuul-server:
#    image: zuul-server-image
#    ports:
#      - 8082:8080  
#           
#  store-api:
#    image: store-api-image
#    depends_on:
#      - mysql
#    ports:
#      - 8083:8080
# 
#  order-api:
#    image: order-api-image
#    depends_on:
#      - mysql
#    ports:
#      - 8084:8080
