version: '3'
services:
  postgres:
    image: postgres:10.4
    environment:
      - POSTGRES_DB=invillia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      
#  keycloak-server:   
#    build:
#      context: ./keycloak
#      dockerfile: Dockerfile
#    image: keycloak-server-image
#    ports:
#      - 8080:8080
        
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    image: eureka-server-image
    ports:
      - 8081:8080
      
  zuul-server:
    build:
      context: ./zuul-server
      dockerfile: Dockerfile
    image: zuul-server-image
    ports:
      - 8082:8080  
           
  store-api:
    build:
      context: ./store-api
      dockerfile: Dockerfile
    image: store-api-image
    depends_on:
      - postgres
    ports:
      - 8083:8080
 
  order-api:
    build:
      context: ./order-api
      dockerfile: Dockerfile
    image: order-api-image
    depends_on:
      - postgres
    ports:
      - 8084:8080

  payment-api:
    build:
      context: ./payment-api
      dockerfile: Dockerfile 
    image: payment-api-image
    depends_on:
      - postgres
    ports:
      - 8085:8080
